### ISSUE TITLE
Access to Receiver.ColorFormat

### ISSUE THREAD

**Issue by bdunkleysmith** [WalkerKnapp/devolay#6]
Hi, using your compiled jar as the basis for a library in B4J as I explained in [#5](https://github.com/WalkerKnapp/devolay/issues/5) I have a testbed application functioning, but while I am I am able to set the FourCCType of the Sender, I'm having difficulties setting the ColorFormat of the Receiver. 

I notice that you have a separate DevolayFrameFourCCType.java file which contains the enum relevant setting the VideoFrame FourCCType, but by comparison the enum relevant setting the Receiver ColorFormat are not in a similar "DevolayReceiverColorFormat.java" file.

This structure may be inherited from the original NewTek SDK, but I can't see how I can set the ColorFormat of the Receiver with my derived library.

However below is an image of my testbed app which shows an image being received via NDI sent from the NewTek Test Pattern tool.

![image](https://user-images.githubusercontent.com/58616953/70849394-d17f4b00-1ed1-11ea-87da-99da654fffb5.png)

**Comment by WalkerKnapp** [comment]
I'm not sure how to apply this to B4J, but the expanded `DevolayReceiver(DevolaySource, ColorFormat, int, boolean)` constructor allows you to set the desired ColorFormat (I should probably make a utility constructor for just setting the ColorFormat, but I haven't yet). 

However, the issue is that, as far as I can tell, the C API doesn't expose a way to get the color format of a receiver once it's created. This makes the `ColorFormat.FASTEST` and `ColorFormat.BEST` formats essentially useless, so I'm not sure why they don't.

Anyways, the default constructor is `new DevolayReceiver(source, DevolayReceiver.ColorFormat.UYVY_BGRA, DevolayReceiver.RECEIVE_BANDWIDTH_HIGHEST, true, null);`. If you want to set a ColorFormat, replacing UYVU_BGRA with the desired enum should work in most cases. From reading the docs, it looks like it's not guaranteed to be supported by all systems, though.

**Comment by bdunkleysmith** [comment]
Thanks for the further information. I've now figured out how to access the Constructors with parameters  and so have been able to set the ColorFormat to BGRX_BGRA as I wanted.

Thanks for your great support!
